### PR TITLE
Added fadeout after 8 seconds

### PR DESCRIPTION
**Pull request by tylerhm**

### CODE REVIEW

**Comment by suneettipirneni** [comment]
I cloned this repo and tried it on my computer the notification just disappears without any animation.

**Comment by tylerhm** [comment]
> I cloned this repo and tried it on my computer the notification just disappears without any animation.

Weird, what browser? Works on Chrome.

**Comment by tylerhm** [comment]
also, does it wait the 8 seconds first?

**Comment by suneettipirneni** [comment]
> also, does it wait the 8 seconds first?

I'm using safari, also yes it does wait 8 seconds before going away

**Comment by tylerhm** [comment]
> > also, does it wait the 8 seconds first?
> 
> I'm using safari, also yes it does wait 8 seconds before going away

[This](https://giphy.com/gifs/MwOTpTrMpQC16hskok) is what I have on my end. Looking for fixes now

**Comment by suneettipirneni** [comment]
> > > also, does it wait the 8 seconds first?
> > 
> > 
> > I'm using safari, also yes it does wait 8 seconds before going away
> 
> [This](https://giphy.com/gifs/MwOTpTrMpQC16hskok) is what I have on my end. Looking for fixes now

My bad I though you were referring to the notifications on the landing page not the login page 😄

**Comment by tylerhm** [comment]
> > > > also, does it wait the 8 seconds first?
> > > 
> > > 
> > > I'm using safari, also yes it does wait 8 seconds before going away
> > 
> > 
> > [This](https://giphy.com/gifs/MwOTpTrMpQC16hskok) is what I have on my end. Looking for fixes now
> 
> My bad I though you were referring to the notifications on the landing page not the login page

They should both be working though, so still odd

**Comment by tylerhm** [comment]
[landing_page working](https://giphy.com/gifs/e7cI2EonYSLiU3yMnZ)

**Comment by suneettipirneni** [comment]
Ok weird it seems to be working now, maybe my files were outdated

**Review by suneettipirneni — APPROVED** [review]

**Comment by tylerhm** [comment]
Nice!

**Pull request merged**
