### PR TITLE
Front-end update to Create Account. 

### PR DESCRIPTION
**Pull request by tylerhm**
Notification handling has also been streamlined, and duplicate notification popups are fixed.
Library of previews can be viewed [here](https://imgur.com/a/DmPV00j).

### Notification Change
`displayError(title, desc)` has been removed, and replaced with `displayNotification(title, desc, type)`
To use, specify type `"success"` or `"error"` for green or red box respectively.

### CODE REVIEW

**Comment by suneettipirneni** [comment]
This looks great!

I think I'll try separating the login card html so we can reuse it rather than copy and pasting it between html files and I'll push the changes to this branch.

**Comment by tylerhm** [comment]
Thanks! Sounds good :)

**Comment by suneettipirneni** [comment]
> This looks great!
> 
> I think I'll try separating the login card html so we can reuse it rather than copy and pasting it between html files and I'll push the changes to this branch.

Ignore this, it's a lot of work for something simple. This should be go to go now

**Review by suneettipirneni — APPROVED** [review]

**Comment by tylerhm** [comment]
> > This looks great!
> > I think I'll try separating the login card html so we can reuse it rather than copy and pasting it between html files and I'll push the changes to this branch.
> 
> Ignore this, it's a lot of work for something simple. This should be go to go now

Got it

**Pull request merged**
