### PR TITLE
Js api/contact search

### PR DESCRIPTION
**Pull request by tylerhm**

### CODE REVIEW

**Review by suneettipirneni — CHANGES_REQUESTED** [review]
The creation of contacts is already taken care of in `userController.php`, so I don't think we need a separate file for that.

**Comment by tylerhm** [comment]
> The creation of contacts is already taken care of in `userController.php`, so I don't think we need a separate file for that.

100% agree. We need to make some modifications to incorporate the City State and ZIP fields.

**Comment by suneettipirneni** [comment]
Now that I think of it, I might be better to separate our js out, for example put the contact/related code in a file called "contact.js"

**Comment by tylerhm** [comment]
> Now that I think of it, I might be better to separate our js out, for example put the contact/related code in a file called "contact.js"

I agree, as we flesh it out more it will be useful to have that differentiation.

**Review by suneettipirneni — APPROVED** [review]

**Pull request merged**
